CREATE TABLE `ps_map_data_source_dods` (
  `dataid` int unsigned NOT NULL default '0',
  `allieskills` smallint unsigned NOT NULL default '0',
  `axiskills` smallint unsigned NOT NULL default '0',
  `joinedallies` smallint unsigned NOT NULL default '0',
  `joinedaxis` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `allieswon` smallint unsigned NOT NULL default '0',
  `allieslost` smallint unsigned NOT NULL default '0',
  `axiswon` smallint unsigned NOT NULL default '0',
  `axislost` smallint unsigned NOT NULL default '0',
  `bombplanted` smallint unsigned NOT NULL default '0',
  `bombdefused` smallint unsigned NOT NULL default '0',
  `killedbombplanter` smallint unsigned NOT NULL default '0',
  `alliesflagscaptured` smallint unsigned NOT NULL default '0',
  `axisflagscaptured` smallint unsigned NOT NULL default '0',
  `flagscaptured` smallint unsigned NOT NULL default '0',
  `alliesflagsblocked` smallint unsigned NOT NULL default '0',
  `axisflagsblocked` smallint unsigned NOT NULL default '0',
  `flagsblocked` smallint unsigned NOT NULL default '0',
  `alliesscore` smallint unsigned NOT NULL default '0',
  `axisscore` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;
CREATE TABLE `ps_plr_data_source_dods` (
  `dataid` int unsigned NOT NULL default '0',
  `allieskills` smallint unsigned NOT NULL default '0',
  `axiskills` smallint unsigned NOT NULL default '0',
  `alliesdeaths` smallint unsigned NOT NULL default '0',
  `axisdeaths` smallint unsigned NOT NULL default '0',
  `joinedallies` smallint unsigned NOT NULL default '0',
  `joinedaxis` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `allieswon` smallint unsigned NOT NULL default '0',
  `allieslost` smallint unsigned NOT NULL default '0',
  `axiswon` smallint unsigned NOT NULL default '0',
  `axislost` smallint unsigned NOT NULL default '0',
  `bombplanted` smallint unsigned NOT NULL default '0',
  `bombdefused` smallint unsigned NOT NULL default '0',
  `killedbombplanter` smallint unsigned NOT NULL default '0',
  `alliesflagscaptured` smallint unsigned NOT NULL default '0',
  `axisflagscaptured` smallint unsigned NOT NULL default '0',
  `flagscaptured` smallint unsigned NOT NULL default '0',
  `alliesflagsblocked` smallint unsigned NOT NULL default '0',
  `axisflagsblocked` smallint unsigned NOT NULL default '0',
  `flagsblocked` smallint unsigned NOT NULL default '0',
  `alliesscore` smallint unsigned NOT NULL default '0',
  `axisscore` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;
CREATE TABLE `ps_plr_maps_source_dods` (
  `dataid` int unsigned NOT NULL default '0',
  `allieskills` smallint unsigned NOT NULL default '0',
  `alliesdeaths` smallint unsigned NOT NULL default '0',
  `axiskills` smallint unsigned NOT NULL default '0',
  `axisdeaths` smallint unsigned NOT NULL default '0',
  `joinedallies` smallint unsigned NOT NULL default '0',
  `joinedaxis` smallint unsigned NOT NULL default '0',
  `joinedspectator` smallint unsigned NOT NULL default '0',
  `allieswon` smallint unsigned NOT NULL default '0',
  `allieslost` smallint unsigned NOT NULL default '0',
  `axiswon` smallint unsigned NOT NULL default '0',
  `axislost` smallint unsigned NOT NULL default '0',
  `bombplanted` smallint unsigned NOT NULL default '0',
  `bombdefused` smallint unsigned NOT NULL default '0',
  `killedbombplanter` smallint unsigned NOT NULL default '0',
  `alliesflagscaptured` smallint unsigned NOT NULL default '0',
  `axisflagscaptured` smallint unsigned NOT NULL default '0',
  `flagscaptured` smallint unsigned NOT NULL default '0',
  `alliesflagsblocked` smallint unsigned NOT NULL default '0',
  `axisflagsblocked` smallint unsigned NOT NULL default '0',
  `flagsblocked` smallint unsigned NOT NULL default '0',
  `alliesscore` smallint unsigned NOT NULL default '0',
  `axisscore` smallint unsigned NOT NULL default '0',
  PRIMARY KEY  (`dataid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8mb4 COLLATE utf8mb4_general_ci;

-- Moved from defaults.sql.
INSERT INTO `ps_config_events` (`id`, `gametype`, `modtype`, `eventname`, `alias`, `regex`, `idx`, `ignore`, `codefile`) 
    VALUES 
        (1,'source','','kill','','/^\"(.+(?:<[^>]*>))\" killed \"(.+(?:<[^>]*>))\" with \"([^\"]*)\"(.*)/',10,0,''),
        (2,'source','','attacked','','/^\"(.+(?:<[^>]*>))\" attacked \"(.+(?:<[^>]*>))\" with \"([^\"]+)\"(.*)/',20,1,''),
        (3,'source','','plrtrigger','','/^\"(.+(?:<[^>]*>))\" triggered \"([^\"]+)\"(.*)/',30,0,''),
        (4,'source','','round','','/^World triggered \"([^\"]+)\"(.*)/',40,0,''),
        (5,'source','','entered_game','','/^\"(.+(?:<[^>]*>))\" entered the game(.*)/',50,0,''),
        (6,'source','','joined_team','','/^\"(.+(?:<[^>]*>))\" joined team \"([^\"]+)\"/',60,0,''),
        (7,'source','','suicide','','/^\"(.+(?:<[^>]*>))\" committed suicide with \"([^\"]+)\"(.*)/',70,0,''),
        (8,'source','','changed_name','','/^\"(.+(?:<[^>]*>))\" changed name to \"([^\"]+)\"/',80,0,''),
        (9,'source','','connected','','/^\"(.+(?:<[^>]*>))\" connected, address \"([^\"]+)\"/',90,0,''),
        (10,'source','','connected_steamid','','/^\"(.+(?:<[^>]*>))\" (?:STEAM|VALVE) USERID (.+)/',100,0,''),
        (11,'source','','disconnected','','/^\"(.+(?:<[^>]*>))\" disconnected/',110,0,''),
        (12,'source','','chat','','/^\"(.+(?:<[^>]*>))\" say(_team)* \"(.*)\"?(.*)/',120,0,''),
        (13,'source','','rcon','','/^(Bad )?Rcon: \"rcon (-*\\d+) \"?(.*?)\"? (.+?)(?:\" from \"([^\"]+)\")?/',130,1,''),
        (14,'source','','cheated','','/^Secure: \"(.+(?:<[^>]*>))\" was detected cheating/',140,0,''),
        (15,'source','','ban','','/^(Addip|Ban(?:id)?): \"([^\"]+)\" was (?:kicked and )?(?:banned)(?: by IP)? \"([^\"]+)\" by \"([^\"]+)\"(.*)/',150,1,''),
        (16,'source','','unban','','/^Remove(id|ip): \"([^\"]+)\" was unbanned by \"(.+(?:<[^>]*>))\"(.*)/',160,1,''),
        (17,'source','','kick','','/^Kick: \"(.+(?:<[^>]*>))\" was kicked by \"(.+(?:<[^>]*>)?)\"(.*)/',170,0,''),
        (18,'source','','pingkick','','/^\"(.+(?:<[^>]*>))\" kicked due to high ping(.*)/',180,0,''),
        (19,'source','','ffkick','','/^\"(.+(?:<[^>]*>))\" has been auto kicked from the game for TKing/',190,0,''),
        (20,'source','','startedmap','','/^(Started|Loading) map \"([^\"]+)\"(.*)/',200,0,''),
        (21,'source','','logstartend','','/^Log file (started|closed)(.*)/',210,0,''),
        (22,'source','','ignored1','','/^[Ss]erver (?:cvars?|say|shutdown)/',220,1,''),
        (23,'source','','ignored2','','/^(?:\\]TSC\\[|Succeeded|FATAL|-|Loaded)/',230,1,''),
        (24,'source','','ignored3','','/^(?:Config|Swear|server_)/',240,1,''),
        (25,'source','','ignored4','','/^\"[^\"]+\" = \"/',250,1,''),
        (30,'source','dods','plrtrigger','','/^\"(.+(?:<[^>]*>))\" triggered(?: a)? \"([^\"]+)\"(.*)/',300,0,''),
        (31,'source','dods','dods_scores','','/^Team \"([^\"]+)\" (scored|captured)/',310,1,''),
        (32,'source','dods','dods_ignore1','','/^\"(.+(?:<[^>]*>))\" blocked/',320,1,''),
        (33,'source','','changed_role','','/^\"(.+(?:<[^>]*>))\" changed role to \"([^\"]+)\"/',330,0,''),
        (34,'source','dods','dods_objitem','','/^\"(.+(?:<[^>]*>))\" triggered an objective item/',340,1,''),
        (35,'source','dods','dods_teamscore','','/^\"([^\"]+)\" scored \"([^\"]+)\" with \"([^\"]+)\" players/',350,0,''),
        (36,'source','dods','teamtrigger','','/^Team \"([^\"]+)\" triggered(?: a)? \"([^\"]+)\"(.*)/',360,0,''),
        (37,'source','dods','dods_ignore1','','/^(?:Final)/',370,1,''),
        (45,'source','','rcon2','','/^rcon from/',130,1,''),
        (48,'source','','spatial','','/^\\[KTRAJ\\] \"(.+(?:<[^>]*>))\" killed \"(.+(?:<[^>]*>))\" with \"([^\"]*)\"(.*)/',480,0,''),
        (49,'source','','plugin','','/^\\[[^\\]]+\\]/',490,1,''),
        (50,'source','','console','','/^(CONSOLE|PLAYER FILTER) :/',500,1,''),
        (100,'source','','ignored5','','/^Server name is \"([^"]+)\"/',1000,1,''),
        (101,'source','','ignored6','','/^Connection to Steam servers successful./',1010,1,''),
        (102,'source','','ignored7','','/^VAC secure mode is activated./',1020,1,''),
        (103,'source','','ignored8','','/^Assigned anonymous gameserver Steam ID \[(.:\\d:\\d+:\\d+)\]./',1030,1,''),
        (104,'source','','ignored9','','/^Public IP is ([0-9A-Fa-f]{1,4}:){7}[0-9A-Fa-f]{1,4}|(\\d{1,3}\.){3}\\d{1,3}./',1040,1,'');

INSERT INTO `ps_config_plrbonuses` (`id`, `eventname`, `enactor`, `enactor_team`, `victim`, `victim_team`, `description`, `gametype`, `modtype`) 
    VALUES 
        (15,'bomb_defuse',2,1,-1,0,'A player defused a bomb','source','dods'),
        (16,'bomb_plant',2,1,0,0,'A player planted a bomb','source','dods'),
        (17,'dod_blocked_point',1,0,0,0,'1 or more players blocked a control point before it could be captured from the enemy team.','source','dods'),
        (18,'dod_capture_area',2,0,0,0,'1 or more players captured a flag area','source','dods'),
        (19,'dod_control_point',2,0,0,0,'A Player captured a flag point','source','dods'),
        (20,'kill_planter',5,0,0,0,'A player killed a player while they were attempting to plant a bomb.','source','dods'),
        (34,'ffkill',-10,0,0,0,'when a player kills a team mate','','');

INSERT INTO `ps_config_awards` (`id`, `enabled`, `idx`, `type`, `negative`, `class`, `name`, `groupname`, `phrase`, `expr`, `order`, `where`, `limit`, `format`, `gametype`, `modtype`, `rankedonly`, `description`) 
    VALUES 
        (4,1,10,'player',0,'','Highest Skill','','{$player.link} has the highest skill with {$award.value}','{$skill}','desc','',0,'%.02f',NULL,NULL,1,'Player with the highest skill'),
        (6,1,20,'player',0,'','Most Kills','','{$player.link} has killed the most players ({$award.value})','{$kills}','desc','',0,'commify',NULL,NULL,1,'Player with the most kills (any team)'),
        (8,1,70,'player',0,'','Most Time Online','','{$player.link} has been online the longest ({$award.value})','{$onlinetime}','desc','',25,'compacttime',NULL,NULL,1,'Player with the most online time'),
        (9,1,190,'weaponclass',0,'','Most Kills with {$weapon.class} weapons','','{$player.link} has the most {$weapon.class} kills ({$award.value})','{$kills}','desc','',0,'commify',NULL,NULL,1,'Most kills with {$weapon.class} type weapons (including: {$weapon.list}).'),
        (10,1,180,'weapon',0,'','Most Kills with {$weapon.name}','','{$player.link} has the most {$weapon.link} kills ({$award.value})','{$kills}','desc','',0,'commify',NULL,NULL,1,'Most kills with a {$weapon.name}'),
        (13,1,30,'player',0,'','Most Bonus Points','','{$player.link} achieved the most bonus points ({$award.value})','{$totalbonus}','desc','',25,'commify',NULL,NULL,1,'Player that has achieved the most bonus points.'),
        (17,1,165,'player',0,'','Most Allied Flags Captured','','{$player.link} has the most Allied flag captures ({$award.value} flags)','{$alliesflagscaptured}','desc','',10,'commify','source','dods',1,'Most flags captured as an ally.'),
        (19,1,170,'player',0,'','Most Axis Flags Captured','','{$player.link} has the most Axis flag captures ({$award.value} flags)','{$axisflagscaptured}','desc','',10,'commify','source','dods',1,'Most flags captured as an Axis.'),
        (22,1,140,'player',0,'','Most Flags Captured','','{$player.link} has captured the most flags ({$award.value})','{$flagscaptured}','desc','',10,'commify','source','dods',1,'Player has captured the most flags.'),
        (23,1,50,'player',1,'','Worst Teammate','','{$player.link} has killed the most teammates ({$award.value})','{$ffkills}','desc','',0,'commify',NULL,NULL,1,'Player with the most friendly fire kills (ie: Worst Teammate)'),
        (25,1,60,'player',1,'','Worst Team Kill Percentage','','{$player.link} has the highest team kill percentage ({$award.value})','{$ffkills} / {$kills} * 100','desc','',0,'%0.02f%%',NULL,NULL,1,'Player with the highest team kill percentage.'),
        (28,1,160,'player',0,'','Most Flags Defended','','{$player.link} has defended the most flags ({$award.value})','{$flagsdefended}','desc','',1,'%s','source','dods',1,'Player who has defended (or returned) the most flags from the enemy.');
